BenSampo/laravel-enum

src/Enum.php, tests/EnumTest.php, tests/UserType.php
For some obscure reason a lot of developers (including me) resort to uppercasing all constants:
```php
final class Foo extends Enum {
const ONE = 1;
const TWO = 2;
}
```
Currently the auto generated description yields superfluous spaces because of the `snake_case` call:
```
o n e
t w o
```
This PR just adds a simple check.
=> Support uppercase constants

.travis.yml
Hi,
Thanks for awesome library.
I noticed we are not testing this library against most recent versions of php.
This PR makes it possible to test against multiple versions.
This is the most recommended way to cover majority of users.
Read more here:
https://evertpot.com/testing-composer-prefer-lowest/
You can see how it goes on TravisCI
https://travis-ci.org/BenSampo/laravel-enum/builds/494119222
Thanks.
=> Test against php 7.2 and 7.3 too

src/Enum.php, src/EnumInstanceTrait.php, src/Stubs/Enum.stub, tests/EnumInstanceTest.php, tests/Enums/MixedKeyFormats.php, tests/Enums/StringValues.php, tests/Enums/UserType.php, tests/Enums/UserTypeLocalized.php
The reason for this pull request is to allow instances of enum which
allows less error since one can typehint a method, constructor and function
to accept only an instance of that enum.
Since the enums contains only literal which can be easily bypassed by
passing the actual value of the constant.
```php
$userType = UserType::getInstance(UserType::Administrator);
// This way one is rest assured that the
// user's type is from the UserType enum.
createUser(array $data, UserType $userType)
{
if ($userType->equals(UserType::Administrator)) {
// ...;
} else {
// ...;
}
}
```
=> Enum Instance Support

src/Stubs/Enum.stub
Hi,
`php artisan make:enum WeekDay` is generating wrong class,
The `EnumInstanceTrait` is no longer available in package.
=> Remove trait from stub

.gitattributes
Hi,
We can exclude `branding` folder, it will reduce the package size.
=> Exclude branding from git archive

src/Commands/MakeEnumCommand.php, src/Contracts/EnumContract.php, src/Contracts/LocalizedEnum.php, src/Enum.php, src/EnumServiceProvider.php, src/Exceptions/InvalidEnumMemberException.php, src/Rules/EnumKey.php, src/Rules/EnumValue.php, src/Traits/CastsEnums.php
Some type hints were out of date, so i fixed them.
In the Laravel code style, Docblocks look a bit different - i adopted that here as well
to be consistent.
Thanks for a great package, it has been quite helpful!
=> Fix type hints and docblocks to Laravel style

composer.json
This is necessary because Laravel does not use Semantic Versioning, so minor version updates can have breaking changes.
=> Specify the Laravel version up to minor explicitely

README.md, composer.json, extension.neon, src/PHPStan/EnumMethodReflection.php, src/PHPStan/EnumMethodsClassReflectionExtension.php, tests/PHPStanTest.php
If you are using [PHPStan](https://github.com/phpstan/phpstan) for static
analysis, you can enable the extension for proper recognition of the
magic instantiation methods.
Add the following to your projects `phpstan.neon` includes:
```neon
includes:
- vendor/bensampo/laravel-enum/extension.neon
```
=> PHPStan integration

README.md, src/Commands/EnumAnnotateCommand.php, src/EnumServiceProvider.php, tests/ApplicationTestCase.php
If you want your IDE to autocomplete the static instantiation helpers, you can
generate PHPDoc annotations through an artisan command.
php artisan enum:annotate "App\Enums\UserType"
Example output from my project:
```php
<?php
declare(strict_types=1);
namespace App\Models\Patient;
use BenSampo\Enum\Enum;
/**
* @method static static DR
* @method static static DR_MED
* @method static static PROF
* @method static static PROF_DR
* @method static static PROF_DR_MED
*/
final class PatientTitle extends Enum
{
const DR = 'Dr.';
const DR_MED = 'Dr. med.';
const PROF = 'Prof.';
const PROF_DR = 'Prof. Dr.';
const PROF_DR_MED = 'Prof. Dr. med.';
}
```
PHPStorm understands the magic instantiation methods now:
=>  Add command to generate PHPDocs for magic instantiation methods

README.md, src/Enum.php, tests/EnumTest.php
Returns an array of all possible instances of the called enum, keyed by the constant names.
```php
var_dump(UserType::getInstances());
array(4) {
'Administrator' =>
class BenSampo\Enum\Tests\Enums\UserType#415 (3) {
public $key =>
string(13) "Administrator"
public $value =>
int(0)
public $description =>
string(13) "Administrator"
}
'Moderator' =>
class BenSampo\Enum\Tests\Enums\UserType#396 (3) {
public $key =>
string(9) "Moderator"
public $value =>
int(1)
public $description =>
string(9) "Moderator"
}
'Subscriber' =>
class BenSampo\Enum\Tests\Enums\UserType#393 (3) {
public $key =>
string(10) "Subscriber"
public $value =>
int(2)
public $description =>
string(10) "Subscriber"
}
'SuperAdministrator' =>
class BenSampo\Enum\Tests\Enums\UserType#102 (3) {
public $key =>
string(18) …
```
=> Add getInstances method

src/Traits/CastsEnums.php
When data is sent via. a form request, the value comes through as a string, and throws [`InvalidEnumMemberException`](https://github.com/BenSampo/laravel-enum/blob/master/src/Enum.php#L56).
>Value 0 doesn't exist in [0, 1]
You can set the property in the `$casts` array on the model, but this isn't called in the `setAttribute` method at present.
The PR adds in the standard Laravel casts modification on the value.
=> Cast the value before getInstance is called in setAttribute method

README.md, src/Enum.php, tests/EnumCastTest.php, tests/EnumTest.php
- Implement the `__toString()` magic method on Enum Class
- Update tests & documentation
Closes #65
=> feat: allow enums to be cast to string

src/Commands/EnumAnnotateCommand.php, tests/ArtisanCommandsTest.php, tests/Enums/MixedKeyFormatsAnnotated.php
It seems I missed an `array_keys`, and didn't have a test for it (only for models).
I've added the test + fixed the bug, sorry 😞
=> fix: fix double annotations on enums

src/Enum.php
In the next version of Laravel helper functions like `snake_case` do not work. If I recall there's an article someone on Laravel News talking about this change. I've been using the in a project that's using Laravel 5.9 and just ran into this today so I figured I'd send a PR.
=> Laravel 5.9 to remove helper string functions

src/Enum.php, tests/EnumTest.php
This adds an `in` method to enum instances, which can be used like so:
```php
$booking->status->in([Status::DRAFT, Status::PENDING, Status::REVIEW])
```
It also supports turning off strict mode by passing `false` as the second parameter. 
Closes #79
=> feat: add `in` method on enum

README.md, src/Enum.php, tests/EnumComparisonTest.php, tests/EnumInstanceTest.php, tests/EnumTest.php
This PR adds the capability to directly compare Enum instances with each other and with arbitrary values.
Comparing against values that are not valid allowed values of the Enum now simply returns `false` instead of throwing.
You can check the equality of an instance against any value by passing it to the `is` method.
``` php
$admin = UserType::getInstance(UserType::Administrator);
$admin->is(UserType::Administrator);   // true
$admin->is($admin);                    // true
$admin->is(UserType::Administrator()); // true
$admin->is(UserType::Moderator);       // false
$admin->is(UserType::Moderator());     // false
$admin->is('random-value');            // false
```
You can also check to see if the instance's value matches against an array of possible values using the `in` method.
```php …
```
=> Make equality checks work with both enum instances and arbitrary values

README.md, src/Enum.php, tests/EnumComparisonTest.php
A purely cosmetic change to the code that would be written by users of this package: perhaps a more 'Laravel' way of writing code. No related issue.
**Changes**
Instead of writing `! is()`, we can now write `isNot()`, (e.g.):
Previously: `return ! $user->role->is(UserRole::Admin);`
With this PR: `return $user->role->isNot(UserRole::Admin);`
I believe that `isNot()` is clearer than `! is()`. But this is purely subjective and I won't be at all offended if this PR is closed. :)
(Also there was some accidental minor cleanup of white space done by my editor.)
None.
=> Added an 'isNot()' method, purely for convenience.

src/Rules/EnumKey.php, src/Rules/EnumValue.php, tests/EnumKeyTest.php, tests/EnumValueTest.php
Occasionally its necessary to serialize Laravel rules to a string. This adds `__toString` serialization to both `EnumKey` and `EnumValue` (see `Illuminate\Validation\Rules\In` for an example inside of Laravel).
**Changes**
This simply adds `__toString` to both provided rules.
N/A
=> Add __toString to Enum rules

composer.json
There is no Laravel 5.9, it will be tagged as 6.0
=> Support Laravel 6.x

src/Traits/CastsEnums.php
N/A
**Changes**
Returns the model when using `setAttribute`. Currently, it doesn't return the model if the attribute doesn't have a enum cast which breaks the intended behaviour of Eloquent. This fix simply returns the call to the `setAttribute` on the parent.
N/A
=> Update setAttribute to return the parent method

src/Enum.php
- [n/a] Added or updated tests
- [n/a] Added or updated the [README.md](../README.md)
This fixes a warning in some IDEs about returning an Enum rather than the actual class type
**Changes**
IDEs no longer warn about return of type Enum
=> Use static|null

composer.json
This enables users of `phpstan/extension-installer` to automatically register the extension provided by `laravel-enum`.
Just like Laravel's automatic package registration, this provides extra convencience.
=> Autoinstall through https://github.com/phpstan/extension-installer

README.md, composer.json, src/EnumServiceProvider.php, src/EnumType.php, tests/EnumTypeTest.php
**Changes**
I documented how `Enum` classes can be utilized to define enum columns, as i use that quite often. It might not be obvious to new users.
Because `doctrine/dbal` lacks an `enum` column type, changing a previously defined column is not straightforward. I registered a custom type through the service provider that makes it work.
No
=> Document migration usage and fix ->change()

src/Traits/CastsEnums.php, tests/EnumCastTest.php, tests/Models/WithTraitButNoCasts.php
~~- [ ] Added or updated the [README.md](../README.md)~~
When adding the `CastsEnum` trait but not adding `$castsEnums` yet, the following error is thrown:
```
1) BenSampo\Enum\Tests\EnumCastTest::test_model_with_trait_but_no_casts
array_key_exists() expects parameter 2 to be array, null given
/projects/laravel-enum/src/Traits/CastsEnums.php:66
/projects/laravel-enum/src/Traits/CastsEnums.php:39
/projects/laravel-enum/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:1535
/projects/laravel-enum/tests/EnumCastTest.php:72
```
This is confusing and can be a nuisance when adding/removing enum casts when refactoring.
**Changes**
Handle unset `$enumCasts` gracefully.
None.
=> Handle missing $enumCasts property gracefully in CastsEnums

CHANGELOG.md, composer.json, src/PHPStan/EnumMethodReflection.php
~~- [ ] Added or updated tests~~
~~- [ ] Added or updated the [README.md](../README.md)~~
**Changes**
Adapt `\BenSampo\Enum\PHPStan\EnumMethodReflection` to work with PHPStan 0.12, they added some new methods to the interface.
I also started a `CHANGELOG.md`, i found it to be a great way to inform users about updates in the package.
Actually no, the changes are additive and still work with PHPStan 0.11
=> Fix compatibility with PHPStan 0.12

src/EnumServiceProvider.php
Fix RuntimeException : A facade root has not been set.
Resolves #118 giving ability to use in Lumen
**Changes**
Replace Facade Validator to build-in.
none
=> Fix for Lumen when Facade not set

CHANGELOG.md, src/Enum.php, tests/EnumComparisonTest.php, tests/Enums/IntegerValues.php
Resolves #128 
**Changes**
Change order of `value` and `key` attribute inside Enum class
Making this change enables relational comparison (using <, >) according to
https://www.php.net/manual/en/language.oop5.object-comparison.php#98725
none
=> Change order of `value` and `key` attribute inside Enum class

CHANGELOG.md, src/Rules/EnumValue.php, tests/EnumValueTest.php
This changes the validation for flagged enums. I would consider the current behaviour as undesired. This might impact someones code.
=> EnumValue validation rule allows multiple flags for FlaggedEnums

CHANGELOG.md, README.md, src/Enum.php, src/Exceptions/InvalidEnumKeyException.php, src/FlaggedEnum.php, src/Traits/CastsEnums.php, tests/EnumComparisonTest.php, tests/EnumInstanceTest.php, tests/EnumTypeHintTest.php, tests/FlaggedEnumTest.php
This use case has come up for us because we use Enum's in two ways:
- values are used for efficient storage in the database
- keys are used for a nice client API
**Changes**
Add new instantiation methods `Enum::fromKey()` and `Enum::fromValue()`
Deprecate `Enum::getInstance()` in favor of `Enum::fromValue()`, as the
new name is consistent with `Enum::fromKey()`
None, but i propose to remove `getInstance()` in an upcoming major version.
=> Add new instantiation methods `Enum::fromKey()` and `Enum::fromValue()`

resources/lang/en/messages.php, src/EnumServiceProvider.php
#134
**Changes**
Localization added by #134 make a little mess with translation file loading order.
Removing translation from ServiceProvider make back to track.
=> Localization order

enum-library.md
A very simple addition that adds an enum library for RFC 5424 log levels.
**Changes**
Edit of the  `./enum-library.md` to include a reference to a new enum library for RFC 5424 log levels.
=> Add RFC 5424 log level enum library

CHANGELOG.md, src/Enum.php, tests/EnumInstanceTest.php, tests/EnumTest.php, tests/Enums/UserType.php
- ~[ ] Added or updated the [README.md](../README.md)~
Here is a actual code we use that did not work as expected:
```php
use BenSampo\Enum\Enum;
/**
* @method static Workgroup ROUTINE()
* @method static Workgroup MLL5K()
* @method static Workgroup MLL5Kv2()
*/
final class Workgroup extends Enum
{
protected const ROUTINE = 'Routine';
protected const MLL5K = 'MLL5K';
protected const MLL5Kv2 = 'MLL5Kv2';
/**
* @return array<self>
*/
public function allPrioritized(): array
{
switch ($this->value) {
case self::MLL5K:
return [
self::MLL5K(),
self::ROUTINE(),
self::MLL5Kv2(),
];
case self::MLL5Kv2:
return [
self::MLL5Kv2(),
self::ROUTINE(),
self::MLL5K(),
];
default:
return [
self::ROUTINE(),
self::MLL5K(),
self::MLL5Kv2(),
];
}
}
}
```
Calling …
=> Handle calling magic instantiation methods from within instance methods of the Enum

README.md, UPGRADE.md, composer.json, src/Casts/EnumCast.php, src/Enum.php, tests/Enums/UserType.php, tests/Enums/UserTypeCustomCast.php, tests/Models/NativeCastModel.php, tests/NativeEnumCastTest.php
WIP PR for implementing native eloquent casting.
Current issues:
- ~Currently, we let laravel do native casting, then we apply the enum cast after.~
~Ie. `'6'` cast by laravel -> `6` cast by us -> `EnumInstance`~
~With the new native casts, this isn't possible. I'm thinking we'll need to pass an additional attribute to the constructor to apply a native cast if required.~
~Kind of a bit messy, but not sure if there's a better way?~
Fixed in the latest commit :)
Also, it seems that natively cast attributes are not used in the `toArray()` which is a breaking change, so we need to see if we can return the object.
Edit: also need some way of only running this test on L7 in CI. Should be easy to do via ENV :)
=> Laravel 7 native casts

CHANGELOG.md, README.md, src/Casts/EnumCast.php, tests/Enums/UserTypeCustomCast.php, tests/NativeEnumCastTest.php
When using the native casting introduced in v2.0 I noticed that returning `null` from the `parseDatabase` method would result in error as it would still try to create an Enum instance from the returned value.
My use case is a modernization of a legacy codebase (25 years old) where some blank data is stored as empty strings instead of `NULL`s in the database.
So when running code like this:
~~~php
public static function parseDatabase($value)
{
if (\blank($value)) {
return null;
}
return (int) $value;
}
~~~
Application would throw an exception on blank values (`null` or empty string).
For this particular project I ended adding a `NA` enum value and defaulting to that for blank values. This is not an ideal solution as the code that relies on the Enum value, and code …
=> Allow to return null on native cast

README.md, src/Enum.php
This PR is kind of a combination of a few issues. Mainly, it fixes the breaking change that was renaming `toSelectArray()` on a minor version.
This broke a few of my apps, and broke another client's app today.
There was also another breaking change (switching the behaviour of `toArray`). I understand this was done to match the v1 behaviour, but I think this should have been a major version bump.
I don't think it's a good idea to change this again, as it would be another breaking change, so I've added a readme section to show how you can restore that behaviour. 
**Changes**
- Fix `toSelectArray` breaking change by reinstating method (but marking is as deprecated)
- Add readme documentation of returning previous v2 `toArray` behaviour. 
None. …
=> fix:`toSelectArray` breaking change + document `toArray` change

tests/EnumKeyTest.php, tests/EnumLocalizationTest.php, tests/EnumTest.php, tests/EnumValidationTest.php, tests/EnumValueTest.php, tests/FlaggedEnumTest.php, tests/PHPStanTest.php
- Using the `assertSame` to make assert value equals strict.
- Using the `assertNull` to assert value is `null`.
=> Using the assertEquals to make value equals strict

.github/workflows/tests.yml, composer.json
**Changes**
This pull request let this package support PHP 8.0.
Because there is `prefer-lowest` testing matrix, to solve testing error, there are two new dependence requirements. (`nikic/php-parser` and `mockery/mockery`)
Without `prefer-lowest` testing matrix, these new dependencies are not required.
=> Support PHP 8.0

CHANGELOG.md, README.md, src/Enum.php, tests/EnumComparisonTest.php
I often have to deal with enums in collections. Having to cast said collections back to array when using the `in()` method is mildly inconvenient.
**Changes**
This PR changes the signature of `in()` to accept an `iterable` instead of an `array`.
None
=> Allow passing iterables to Enum::in()

CHANGELOG.md, src/Enum.php, tests/EnumTest.php, tests/Enums/MixedKeyFormats.php
Resolves #209
**Changes**
There is a check in the `getFriendlyKeyName` function which determines if a key is all uppercase, however this doesn't work if the key contains non-alpha characters so I've updated it to work in that scenario and added the additional test cases
=> Fixing issue for descriptions with uppercase keys and numeric suffix

CHANGELOG.md, resources/lang/en/messages.php, src/EnumServiceProvider.php, src/Rules/Enum.php, src/Rules/EnumKey.php, src/Rules/EnumValue.php, tests/EnumLocalizationTest.php, tests/lang/en/validation.php, tests/lang/es/validation.php
Ensures it is easy to customize/localize validation error messages when using the validation rules as classes **or** as strings.
This PR reverts #141, which reintroduced the issue in #133 where using the validation rules as strings (e.g. `enum_value:UserType`) prevented error messages from being displayed properly. #141 didn't really have any explanation of its changes, but what I think it was _trying_ to do was allow users to easily customize the error messages for this package's validation rules. It implemented this the wrong way though, localizing the message strings themselves directly inside the language file. This has a few disadvantages:
- to translate the messages you would have to re-translate the string by adding `"The value you have provided is not a valid enum instance.": …
=> Fix validation error message localization

.github/workflows/tests.yml, CHANGELOG.md, composer.json
Allows the library to be installed and used with PHP 8.1. I am currently getting the following error:
```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- bensampo/laravel-enum[v3.2.0, ..., v3.4.2] require laminas/laminas-code ^3.4 -![image](https://user-images.githubusercontent.com/12158000/141855849-53d89947-1ad7-4424-ae50-544cdfc372d4.png)satisfiable by laminas/laminas-code[3.4.0, 3.4.1, 3.5.0, 3.5.1].
- bensampo/laravel-enum[v1.28.3, ..., v1.38.0] require php ~7.1 -> your php version (8.1.0-dev) does not satisfy that requirement.
- bensampo/laravel-enum[v2.0.0, ..., v2.2.0] require php ^7.2.5 -> your php version (8.1.0-dev) does not satisfy that requirement.
- bensampo/laravel-enum[v3.0.0, ..., v3.1.0] require php ^7.3 -> …
```
=> Ensure compatibility with PHP 8.1

src/Enum.php
Resolves #235 
**Changes**
Fix following notice
> Return type of BenSampo\Enum\Enum::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
Code is backward compatible for all currently supported php versions (^7.3|^8.0)
=> Suppress deprecated notice on PHP8.1

src/FlaggedEnum.php
**Changes**
Fix the return type in the phpdoc block on the `flags` method, to match the return type in the signature itself.
=> Fix return type on FlaggedEnum `flags` method

CHANGELOG.md, README.md, src/Attributes/Description.php, src/Enum.php, tests/EnumAttributeDescriptionTest.php, tests/Enums/DescriptionFromAttribute.php
Make it easier to define descriptions for each enum case.
**Changes**
I've added the ability to add descriptions to each enum case using a PHP8 attribute. This is favoured over defining them in the getDescription method because each description remains close to the case it's describing. It's also easier to see which cases have descriptions and which don't.
```php
final class UserType extends Enum
{
#[Description('Admin')]
const Administrator = 0;
#[Description('Super admin')]
const SuperAdministrator = 1;
}
```
@spawnia This is inspired by [your PR](https://github.com/BenSampo/laravel-enum/pull/239). I was slightly uncomfortable with defining the descriptions using docblocks and since I've updated the packages' min PHP support to 8.0 (because of L9) I thought this …
=> Enum description attribute

src/Enum.php, tests/EnumTest.php
Concerns https://github.com/BenSampo/laravel-enum/issues/244
This documents the current behaviour. However, I do believe we should change it in the next major version - see https://github.com/BenSampo/laravel-enum/issues/244#issuecomment-1035979621
=> Explain the purpose of `Enum::toArray()`

CHANGELOG.md, src/Enum.php, tests/VarExportTest.php
- ~[ ] Added or updated the [README.md](../README.md)~
Resolves https://github.com/BenSampo/laravel-enum/issues/251
**Changes**
Restore enum instance from `var_export()`.
None, this just did not work before.
=> Restore enum instance from `var_export()`

src/Enum.php, tests/EnumAttributeDescriptionTest.php
Resolves #263
**Changes**
Calling `MyEnum::getDescription($value)` with an invalid value now returns an empty string, rather than throwing an error. This is in line with the behaviour in v4.
N/A
=> Fix getAttributeDescription() error

CHANGELOG.md, composer.json, src/Commands/AbstractAnnotationCommand.php
Resolves https://github.com/BenSampo/laravel-enum/issues/249
**Changes**
Require composer/class-map-generator over composer/composer.
Functionality stays the same, but I consider a new dependency a breaking change.
=> Require composer/class-map-generator over composer/composer

CHANGELOG.md, README.md, src/Attributes/Description.php, src/Enum.php, tests/EnumAttributeDescriptionTest.php, tests/EnumTest.php, tests/Enums/DescriptionFromAttribute.php, tests/Enums/InvalidMultipleClassDescriptionFromAttribute.php
We are working with this package alongside [Lighthouse](https://github.com/nuwave/lighthouse). 
As an updated our GQL standards we realized auto generated GQL enums from BenShampo\Enum does not generate a description for the enum, only its values.
This PR propose broadening the usage of the Description attribute, so that it may be used on the Enum class itself.
Next step will be to update the [LaravelEnumType](https://github.com/nuwave/lighthouse/blob/master/src/Schema/Types/LaravelEnumType.php) from Lighthouse to include the description on the generated enum 😄 
**Changes**
* introduce new usage of Description attribute at class level
* add new static method getClassDescription() on Enum
* test new method getClassDescription()
Nope.
=> Allow Description attribute on class

CHANGELOG.md, src/Commands/EnumAnnotateCommand.php
* Resolved "Backtrack limit exhausted" error on big enum file by simplifying the regex
* Added support for Windows style EOL
This pull request addresses the issue of the backtrack limit being exhausted on big enum file and provides a solution by simplifying the regex. Additionally, support for Windows style EOL has been added.
The changes have been thoroughly tested and the changes have been recorded in the CHANGELOG.
I'm not sure how to update existing tests to include Windows compatibility.
=> Fix backtrack error and add Windows EOL support to the annotate command

src/Enum.php
**Changes**
I believe that hasValue should also accept non-empty-string, not only TValue, because if I use enum like this:
```
<?php
namespace App\Enum;
use BenSampo\Enum\Enum;
/**
* @extends Enum<self::*>
*/
class MyEnum extends Enum
{
public const TEST = 'test';
}
?>
```
then static analysis does not allow me to pass any other value to than 'test' to hasValue method, which is wrong, because if I already know that its there, I dont need to call hasValue()
=> allow non-empty-string in hasValue

CHANGELOG.md, src/EnumServiceProvider.php
**Related Issue**
When the boot method is loaded before third-party translation paths, the __() function calls to trigger the preload of all available translations in the global domain (JSON translation files). As a result, any json path registered later is ignored, leading to the discarding of all their translations.
**Changes**
Ensure that the `ValidationFactory` is fully initialized before creating an instance, guaranteeing that the boot process is complete.
=> Prevent translations to be discarded

CHANGELOG.md, README.md, extension.neon, phpstan.neon, src/PHPStan/UniqueValuesRule.php, tests/PHPStan/EnumMethodsClassReflectionExtensionTest.php, tests/PHPStan/Fixtures/DuplicateValue.php, tests/PHPStan/UniqueValuesRuleTest.php
Duplicate enum values lead to runtime errors, e.g. `getInstances()`.
**Changes**
Adds a PHPStan rule that detects duplicate enum values.
None.
=> Add PHPStan rule to detect duplicate enum values

composer.json, src/Commands/EnumAnnotateCommand.php, src/Enum.php, src/Rector/ToNativeUsagesRector.php
Resolves https://github.com/BenSampo/laravel-enum/issues/348
=> Allow installation alongside PHPUnit 11

CHANGELOG.md, phpstan.neon, src/Rector/ToNativeUsagesRector.php, tests/EnumAnnotateCommandTest.php, tests/PHPStan/UniqueValuesRuleTest.php, tests/Rector/ToNativeImplementationRectorTest.php, tests/Rector/ToNativeUsagesRectorTest.php, tests/Rector/Usages/in.php.inc, tests/Rector/Usages/notIn.php.inc
**Changes**
Converts the values given to `in()` or `notIn()` using `iterator_to_array()` if they are not surely an `array` before passing them into `in_array()`.
None.
=> Fix conversion of `in()` and `notIn()` to native enums when called with non-arrays
