src/Rules/EnumValue.php
Support string enums for the use of MySql ENUM datatype.
=> Add support for string enums

src/Stubs/Enum.stub, tests/EnumTest.php, tests/UserType.php
This enables 100% code coverage on `Enum.php` file.
=> add more tests and better API consistency

src/Enum.php, tests/EnumKeyTest.php, tests/EnumTest.php
- made hasKey case sensitive
- expanded test for case sensitive hasKey
see issue #42
=> Made hasKey case sensitive

README.md, composer.json, src/Commands/EnumAnnotateCommand.php, tests/ArtisanCommandsTest.php, tests/Enums/Annotate/.gitignore, tests/Enums/AnnotateOriginals/AnnotateTestOneEnum.php, tests/Enums/AnnotateOriginals/AnnotateTestTwoEnum.php, tests/fixtures/annotated_class_one, tests/fixtures/annotated_class_two
- Update annotate command to support annotating folders
- Update tests to cover artisan commands
- Update Documentation
I wasn't sure exactly how to organise fixtures, so let me know if you prefer a different style.
Closes #64
=> feat: automatically annotate enums

README.md, src/Enum.php, tests/EnumRandomTest.php, tests/Enums/SingleValue.php
Returns a random instance of the enum. Useful for factories.
```php
UserType::getRandomInstance(); // Returns an instanceof UserType with a random value
```
=> Add Enum::getRandomInstance()

enum-library.md
N/A
**Changes**
Added link to enum library in readme
N/A
=> Added country calling code library

.travis.yml, CHANGELOG.md, composer.json
This just bumps up the dependency constraints to allow for Laravel 7 (which will be released tomorrow!)
=> Add Laravel 7 support

src/EnumServiceProvider.php, tests/EnumPipeValidationTest.php
Resolves https://github.com/BenSampo/laravel-enum/issues/127
Please let me know if the PR needs any changes.
=> add enum validation to service provider

CHANGELOG.md, README.md, resources/lang/en/messages.php, src/EnumServiceProvider.php, src/Rules/Enum.php, src/Rules/EnumKey.php, src/Rules/EnumValue.php
https://github.com/BenSampo/laravel-enum/issues/104
https://github.com/BenSampo/laravel-enum/issues/133
**Changes**
Added translations
Please let me know if the PR needs any changes.
=> Added translations

CHANGELOG.md, README.md, UPGRADE.md, src/Casts/EnumCast.php, src/Commands/AbstractAnnotationCommand.php, src/Commands/EnumAnnotateCommand.php, src/Commands/ModelAnnotateCommand.php, src/Enum.php, src/EnumType.php, src/FlaggedEnum.php, src/Rules/Enum.php, src/Rules/EnumKey.php, src/Rules/EnumValue.php, tests/PHPStanTest.php
- ~[ ] Added or updated tests~
The Changelog should reflect relevent changes.
**Changes**
- Mention breaking dependency upgrade in Changelog
- Fix some PHPDocs and formatting
No
=> Clean up docs and PHPDocs

README.md
=> Update README.md asSelectArray

enum-library.md
Adds a new enum to the library containing HTTP status codes.
**Changes**
Edits the `enum-library.md` file to add the new enum.
No breaking changes.
=> Adds HTTP status codes to enum library

enum-library.md
Adds a new enum to the library containing MIME types.
**Changes**
Edits the enum-library.md file to add the new enum.
No breaking changes.
=> Added MIME types.

CHANGELOG.md, composer.json
**Changes**
- Update doctrine/dbal requirement from ^2.9 to ^2.9|^3.0
=> Update doctrine/dbal requirement from ^2.9 to ^2.9|^3.0

README.md, src/Enum.php, tests/EnumComparisonTest.php
- Added new validation not in 
- updated the [README.md]
- Validation not in and update the comment
=> Add new method not in to check whether a value not in an iterable set of values

.gitattributes, .gitignore, README.md, composer.json, src/Attributes/Description.php
- update .gitattributes
- remove redundant entries from .gitignore
- normalize composer.json
- fix codestyle
- fix link to LICENSE.txt
=> Clean up repository

enum-library.md
-  n/a 
- n/a 
- n/a
n/a
**Changes**
Add flagged Day enum to community [enum library](https://github.com/BenSampo/laravel-enum/blob/master/enum-library.md)
n/a
=> Add flagged day to enum library

src/PHPStan/EnumMethodsClassReflectionExtension.php
Just that.
I leave it 100% up to you! Like an inspiration.
=> Fix boolean handling in EnumMethodsClassReflection

CHANGELOG.md, composer.json, phpstan.neon, src/Enum.php, src/FlaggedEnum.php, tests/EnumAttributeDescriptionTest.php, tests/EnumCastTest.php, tests/EnumKeyTest.php, tests/EnumValidationTest.php, tests/NativeEnumCastTest.php
Resolves https://github.com/BenSampo/laravel-enum/issues/276
=> Add generic type `TValue` to `Enum` class

composer.json, tests/EnumInheritanceTest.php, tests/Enums/Child.php, tests/Enums/ParentEnum.php
Resolves https://github.com/BenSampo/laravel-enum/issues/284
=> Test enum inheritance

phpstan.neon, src/Casts/EnumCast.php
https://github.com/BenSampo/laravel-enum/actions/runs/4164174844/jobs/7205471738
**Changes**
=> Typehint generic `CastsAttributes`

README.md
=> Remove travis badge from README.md

README.md
Resolves https://github.com/BenSampo/laravel-enum/issues/319
=> Prefer lang over resources/lang

src/EnumServiceProvider.php
Although I was not able to reproduce it, this should fix the issue #326  while keeping the fix for later translation loading;
=> Ensure validation rules are always added

README.md
Resolves https://github.com/BenSampo/laravel-enum/issues/346
=> Using this library is no longer recommended
